Rotonde/rotonde-client

.datignore, .gitignore, rotonde.js, scripts/feed.js, scripts/operator.js
this command goes through the port array and resolves all dns shortnames
(e.g. dat://rotonde-beaker-cblgh.hashbase.io) to their actual hashes
(dat://7f2ef715c36b6cd226102192ba220c73384c32e4beb49601fb3f5bba4719e0c5/)
it also adds trailing slashes if they didn't exist
if you do this then you'll fix rune issues stemming from old follows where you used a hashbase address
=> cblgh/features: add fix_port command

links/main.css
I added overflow scroll to left "portal" column. 
- I used padding on top and bottom instead of margins so that the portal column content scrolls similarly to the main column.
- I used padding right on the portal column to keep its scrollbar's distance with its content.
- I added overflow hidden to the portal list to keep long names' distance from the main column.
Ps. This is my first PR ever on an open-source project, hope I got everything else right :-)
=> make left column aside scrollable when there are many portals

scripts/entry.js
When a user tries to edit a post containing single-quote characters, everything after the first quote is cut off in the input box. This fixes that issue.
=> fixed single-quotes inside edited posts

scripts/feed.js
Turns out the URLs reported by dat.json also weren't always accurate either, so instead we have to use DatArchive.resolveName() to get the Definitely Correct URL.
=>  properly fixed URLs in portal list 

rotonde.js, rotonde.spec.js
Was throwing a `global is undefined` error in the browser.
(Turns out I wasn't actually using my local version of `rotonde-client` to view my portal so didn't spot the error!)
=> Fix rotonde to reference window instead of global for jest

rotonde.js, scripts/entry.js, scripts/feed.js, scripts/index.js, scripts/operator.js
Right now, Rotonde queries remote portals in an ad hoc way, mostly
leaving it up to Feed to fetch and store them.  This makes it hard to
show portals outside the ones you're following.  In particular, re-
entries and replies to someone outside your list of portals show up as
raw dat:// URLs.
This patch introduces an "Index" singleton which fetches and stores
remote portals.  You can query them by URL, by name, or using name auto-
complete logic which has been moved from the Operator class.  Instead of
accessing Feed's data structures directly, we ask the Index whenever we
want to get a remote portal.  The Index will return the portal if it has
it, and go fetch it otherwise.
At the same time, simplify Feed so all rendering happens in a single
method.  Index notifies Feed to re-render by …
=> Add an "Index" object to track remote portals

scripts/operator.js
Fixes #53
I tested this pretty extensively (in the manual, and drag and drop cases), but I'm not quite sure what the intent of the removed `split` was. If there is something I missed there, please let me know!
=> Escape file names to accommodate valid characters

links/main.css
Small fix for custom widths where media is overflowing on smaller containers.
=> Make images use full width regardless of entry container size

scripts/entry.js
Changes the formatter to operate on individual lines. This fixes issues where newlines are treated as part of a 'word'. For example, in the following post:
http://example.com/
hello world
...the second line would appear as:
> [**hello..**](http://example.com/hello) world
=> Fix formatting across line-breaks

links/main.css, scripts/entry.js
This <del>mines bitcoin</del> adds syntax for `{-strikethrough-}` text, similar to `{*bold*}` and `{_italic_}`.
=> Add syntax for <del>

rotonde.js, scripts/feed.js
currently, when you visit another user's Rotonde page, you see their feed much like they would see it. This sometimes makes it difficult to see what they themselves have posted. this PR changes this, so that by default the feed is filtered for their @name if you are not the owner of the page.
to make it possible to still see their full feed (including posts by others that don't mention them) if one so desires, I made it so that filters get removed immediately upon clicking the "filtering by …" message. feel free to change this behavior if you have a better solution.
=> visitors filter by portalname + validate clear_filter immediately upon injection

scripts/entry.js, scripts/feed.js, scripts/operator.js
(#73)
Short and simple: messages get scanned for `@user` bits, and Rotonde performs a lookup in the feed. The `target` field in the `portal.json` file becomes an array of mentions in order, and the first mention in the message becomes `@0`, the second `@1`, etc.
When fetching messages using multiple mentions, Rotonde does the reverse: scans for `@[integer]` and fetches the portal URL from the `target` array. It is then substituted by the corresponding username.
Rough around the edges, but backwards compatibility is working, as far as I can see. _Needs lots of testing!_
**Issues:**
1. Messages on the feed are scanned for mentions every single time; we should avoid doing this. Messages could have a `processed` bool or something similar.
2. Mentions to people _not_ in your feed or whose …
=> Initial proposal for multiple mentions

links/main.css
- Added sticky headers to the input box and tabs to keep users oriented when scrolling.
- Small adjustments to let rotonde display better in small sized windows and respond accordingly. 
- Input box styling adjustments help make the input more clear for new users. 
There is currently a bug with the sticky headers due to some event listeners that scroll to top when tabs are clicked.
I can reduce this down to just the headers and width adjustments if you want.
=> Add sticky headers & styling tweaks

links/main.css, rotonde.js, scripts/entry.js, scripts/home.js, scripts/portal.js
Rotonde doesn't escape the entry `media`, which allows anyone to hide anything in there.
```json
{
"message": "Horrible idea of the day: #rotonde bot that reposts my Twitter timeline / Twitter client that works via #rotonde.",
"timestamp": 1509975157676,
"media": "<a a='.png",
"target": []
}
```
Same goes to `client_version`:
```json
"client_version": "0.1.67-dev<br><a href='https://twitter.com/0x0ade'>twttr</a>"
```
This changeset escapes the media URL using `encodeURI` and changes the portal version handling to
1. check the first line for the rotonde version
2. allow a second line to mark any "mod version".
I don't know how "strict" it should be, so I left room for _some_ customization of the client version.
```json
"client_version": "0.1.67\ntonne r0"
```
=> Escape media and version (prevent XSS); Handle extra versions

scripts/portal.js
Applying the changes outlined in the discussion here: https://github.com/Rotonde/rotonde-client/pull/99#discussion_r149183661
This commit stores the escaped badge version in a temporary variable (doesn't accidentally modify your `portal.json` anymore) and replaces the "split on newline" with a more general purpose regex. This gets `0.1.68` from `0.1.68-modded` and `0.1.68:mod`, but gets `0.1.68b` from `0.1.68beta` (in case releases with alphabetic suffixes become a thing).
=> Badge version check now powered by regex

links/main.css, scripts/entry.js, scripts/feed.js, scripts/home.js, scripts/operator.js, scripts/portal.js
I honestly don't expect this PR to be merged as-is, but hope that at least parts of it will find their way into rotonde-client.
This will hurt a little because
* I format my code in rotonde-mod differently than the code in rotonde-client
* `Feed.refresh` now counts more than it should (sorry, @eelfroth )
* `r.home.feed.page` is being used in discovery
* The discovery "renderer" is currently part of `Home.update`
The good news, though, is that the pagination and the related element reuse changes reduced the crash rate. We're not manipulating the DOM via `innerHTML` as aggressively anymore. I assume Beaker 0.8 will just deal with DOM updates better?
This adds the following features:
* `Visible/All` in tab title
* Pagination
* Current / last page displayed in tab title
* New commands: …
=> Merge rotonde-mod 0.1.3 with rotonde-client

scripts/entry.js, scripts/feed.js
before, mentions were computed two different ways--one way for the count, another way for filtering, resulting in #102
loads the Entries tab automatically. i broke this a few commits ago, sorry
=> Fix mentions, fix #102

scripts/feed.js, scripts/operator.js
This fixes:
* The feed not resetting the filters properly (fixes broken feed)
* The `++`, `--` commands and `Feed.page_jump` still referring to rotonde-mod helper variables (those should be the last, I hope...)
=> Fix ++, --, page_jump and clear_filter

scripts/entry.js, scripts/feed.js, scripts/home.js, scripts/operator.js, scripts/portal.js
* Some people shared dat URLs with `/index.html` (or similar) appended. `to_hash` now removes anything past the first `/` in the URL.
* `Portal.hashes()` gets all possible hashes from (currently) `portal.url`, `portal.archive.url`, `portal.json.dat`
* `has_hash(hashes_a, hashes_b)` allows us to check the results of `Portal.hashes()` against each other. Optionally, hashes_b can be a single hash. Also optionally, `has_hash` supports urls (it calls `to_hash` internally) just in case we accidentally pass on the URLs un-`to_hash`-ed.
This should fix various mention, whisper, and portal relationship issues when the URLs were malformed, or when the `dat` in `portal.json` wasn't taken into account.
=> Make to_hash trim /* and add Portal.hashes(), has_hash(hashes_a, hashes_b)

scripts/entry.js, scripts/feed.js
* I noticed other whispers being visible on my timeline. I accidentally broke it with #113, sorry about that. Fixed it.
* Very minor thing: The port URL fixer uses the archive URLs, but they don't end with `/`. The port URL fixer now adds the "missing" `/`.
=> Add "/" to URLs in port list if missing; Fix whisper visibility

rotonde.js, scripts/feed.js, scripts/portal.js
Related discussion on Twitter, linking to thread tail: https://twitter.com/lechd/status/929056891409453056
The `dat` field in `portal.json` is just causing issues and @neauoire told me about `DatArchive.resolveName`, which is preferable for every use case in rotonde right now (except for when someone wants to "update" their portal to a new dat).
This makes `portal.hashes()` (used in f.e. `is_known`, mention / whisper checking) effectively return the result of `resolveName`.
`dat` in `portal.json` is now useless (can't find anything using it anymore), but it's still being kept as old client versions use it.
=> Add portal.dat ~ DatArchive.resolveName(url), use it over dat in portal.json

README.md, rotonde.js, scripts/entry.js, scripts/operator.js
was missing some media formats that also work in beaker, so I added them. uncompressed formats seem stupid on the dat web, so I removed support for them.
it was very disorienting that the page scrolled to `(0, 0)` every time you clicked something or started typing, so I fixed that.
\+ I fixed the reason parameter for refresh on validating `say` commads
and I updated the documentation to better reflect the current feature set
=> media formats, no scroll on input, documentation

scripts/feed.js, scripts/home.js, scripts/portal.js
* Code "quality of life": `has_hash` now checks if the left or right side has got a `hashes` function. If so, it calls it and uses its result. This allows us to simply pass the portals to `has_hash`.
* @neauoire I've identified the bug you were experiencing earlier. When posting something (and thus saving), our own portal got refreshed twice, as it exists in both `r.home.portal` and `r.home.feed.portals`. This fixes the "my own posts get glitched to the top when posting" issue :)
=> Make has_hash handle portals as args; Fix refresh on save

scripts/home.js, scripts/operator.js
I really miss the help-on-click from 0.1.6, so I've built one that fits the current version. The `help` command without parameters prints the existing commands. 
I've also needed to change the `home.log` function, because the helps disappeared too fast, but you can use it without the `life` parameters too. 
It's OK if it doesn't gets accepted. :D
=> Added help command

scripts/entry.js, scripts/feed.js, scripts/home.js
This allows the portals to connect way faster. In `Portal.connect`, when a connection succeeds, it still connects to the next portal after 250ms. But when a connection failed, rotonde now immediately tries connecting to the next portal in the queue.
Before this change, it already attempted doing the same, but failed due to the "time of last update" check in `r.home.feed.next`.
The timeouts are unchanged.
This helps greatly when you're following many portals.
Edit: I'm also smuggling a small fix for the `:` rune being used in entry headers even when no targets are given.
=> Speed up connection process - remove r.home.feed.last_update

index.html, site/close.svg, site/icon.svg, site/scripts.js, site/styles.css
As per discussion on #117 I've gone ahead and moved the launchpad in.
@neauoire I'm not sure what all you want to do with the designs, but for conflicts sake here is what I was wanting to work on before this gets merged:
Some other things that I would **eventually** like to do with the site:
- move the majority of the documentation here
- Add a "preferences" page that allows a user to update their settings in a similar fashion.
- Enable the site to fall back to https and prompt the user to download Beaker.
- Offer a selection of default avatars to choose from.
=> Add Rotonde Launchapd

scripts/feed.js, scripts/operator.js, scripts/portal.js
This should fix finally the issue @frozenpandaman is dealing with in #16.
We'll (finally) check the portal's port list against _all_ of our hashes. A "hash" can be `1327ca6d4caf3c4665f5b82d72a5dc716ddf24f58f253e857c5703b9b6a69838` (resolved) or `elifessler.com` (the current domain name).
Latter should get resolved to the actual hash when the portal gets registered, anyway, but it will still cause issues when someone on an older version has got `elifessler.com` in their `ports` and eli is checking their portal from `1327...9898`.
We could try resolving the URLs in followed portals' `port`s, but
1. it'd strain the user's data connection even more
2. it'd cause unnecessary refreshes once we resolved it
3. it will be unnecessary once enough people move on to 1.8+ and after some time passes. …
=> Use hashes() when checking relationships; Fix dat cmd & enhance dat, undat

links/main.css, scripts/entry.js, scripts/feed.js, scripts/operator.js, scripts/portal.js
This implements #43, changing the runes from hardcoded ones to CSS variables.
Runes are split into "contexts" so you can manipulate all runes of one kind at once (f.e. all portal runes).
Effectively, rune elements have the following three classes:
* `rune` - matches all runes
* `rune-{context}` - matches f.e. all operator runes, feed runes, portal runes
* `rune-{context}-{type}` - this is also the variable name, allowing you to manipulate runes from custom.css as you wish
=> Move runes to CSS (implement #43)

links/main.css, scripts/feed.js, scripts/home.js, scripts/operator.js, scripts/portal.js
* I added a small function to help us deal with timeouts not working properly in Beaker pre-0.8. You call it similarly to `setTimeout`, but passing on the promise to wait for instead of a function to run after the timeout. Example: `await promiseTimeout(p.archive.readFile('/portal.json', {timeout: 2000}), 2000);` (`{timeout: 2000}` kept as-is to rely on Beaker 0.8's timeout in the future.)
* The discovery tab now doesn't update in the background, but instead requires the user to press a new "refresh" button (always the first entry). I've also fixed it being too fast and thus consuming too many resources in a too short timespan.
=> Add promiseTimeout helper and make discovery "opt-in"

scripts/entry.js, scripts/operator.js
This fixes the following two issues, both outlined in this comment: https://github.com/Rotonde/rotonde-client/issues/109#issuecomment-343909738
* The media URLs in `portal.json` are already sent through `encodeURIComponent` (shouldn't they be sent through `encodeURI`?). Meanwhile, `entry.rmc` sends them through `encodeURI` *again* and stores the encoded URI as `this.media`, causing an escaping "feedback loop". Thanks to @eelfroth for telling me about this!
* Some accidentally added `media/content/` (escaped: `media%2Fcontent%2F`) to their media URLs. As it's an easy mistake and easy to fix on our end, this PR fixes the "issue" by removing the improperly added prefix from media URLs.
Thank you @eelfroth for notifying me about this!
=> Fix media URI escape issue + some putting "media/content/" into their media URLs

links/main.css, scripts/entry.js, scripts/feed.js, scripts/operator.js, scripts/portal.js
ok, this is kind of a big PR so let me briefly explain each commit.
`da007da`: I noticed that sometimes media attachment URLs had a superfluous `/` and couldn't be displayed because of that → fixed!
`a7b8c0b`: when you quoted a message that has inline emoji, the client looked for the images in the quoter's portal (not the quotee's) → fixed!
`372f75a`: this introduces rendering of quote-threads! if there is more than one quote (as in, the quote has a quote, etc.), a "expand `n` quotes" message appears. clicking it will validate `expand:name-ref`, and the thread will be shown. clicking "collapse quotes" on an expanded thread will validate `collapse:name-ref`, and the thread is hidden once more. threads → implemented!
`5180280`: this re-fixes the issue that you would lose your scroll …
=> threads! (+ some fixes)

links/main.css
hey this is a quick solution I found to the disappearing tabs issue.
the fix works for me and the handful of other portals I tried it on but can't guarantee it won't break someones styling somewhere
for reference - my portal: dat://a5341c28d55680dfbe073df05a01e9d58591a782e5ca252d60b2ce62935b4498/
hope random pull requests are okay!
=> Potential fix for disappearing tabs on discovery and portals pages

scripts/entry.js, scripts/feed.js, scripts/home.js, scripts/operator.js, scripts/portal.js
`portal.updated()` now correctly checks for the most recent entry (both timestamp and editstamp-wise). Before, it just blindly picked the last entry in the list.
Also, `json.port` gets sorted by activity on `home.save`.
I initially thought about sorting it in `feed.register`, but opted against it. Feeds can update on the fly and the order determined in `feed.register` can already be outdated when saving.  
Additionally, this doesn't "magically fix" your portal.json. You still need to invoke a save by f.e. following someone or posting something. Automatically invoking a save after sorting would just bloat the history.
Edit: Yet again, I'm smuggling in an unrelated fix. When using the undat command, entries from the unfollowed portal still ghosted around. This PR introduces …
=> Sort port list by activity, fix portal.updated(), misc fixes

scripts/entry.js
this pr fixes shortening of already short http links (i.e. stops appending of .. to short links)
it also makes it possible to link [passages](http://www.dictionary.com/browse/passage) of text using `[markdown style](https://guides.github.com/features/mastering-markdown/#examples)`
i'm doing this as a pr since it's been a subjective while since i last contributed, and the previous time i made a patch with regexes turned out, ehm, sub-optimal. 
potential concerns! the (url) regex isn't strict at all, so you can basically `[link](whatever)`
i'm not sure how much of a problem that will pose, i don't think it should allow for executing javascript since we escape the html before we even get to this stage
anyway i think this feature will be great for **The Daily Descent** among other things :~
=> improve link shortening & add [descriptive](https://links)

scripts/entry.js
Some portals don't have a "desc" field for whatever reason (I think they're broken/not loading correctly), which breaks rendering of the feed. This is a workaround for that.
=> small fix for displaying entries with missing desc

rotonde.js
This fixes threads not expanding. `entry.icon` tries to escape the host's description, which isn't set in the pseudo portal. `escape_html` and `escape_attr` threw an exception if `!m` (i.e. `m == null`).
TIL: `&&` returns the first falsy value (`"" && 0 && null` returns `""`).
=> Fix escape_html / escape_attr failing on !m

links/main.css, rotonde.js, scripts/entry.js, scripts/feed.js, scripts/home.js, scripts/operator.js, scripts/portal.js
- Implement `move_element` to move elements, thus manipulating the DOM much less aggressively.
This is what `Entry.to_element` / `Portal.add_badge` built towards. Before, all elements were blindly re-added, causing all elements to get invalidated with every "refresh."
- Merge portals list and discovery into the same wrapper.
- Replace (most of) `format_links` with character index based manipulation instead of split & join. Still made it simple to use.
- Give `sort` direct delta (faster sorting in my testing).
- "Cache" (reuse) values _a lot._ No, that's not "caching to disk," but just storing and reusing function results that would otherwise take (relatively) long to get to.
- Optimize `to_hash`.
- Add `Portal.hashes_set()`, allow `has_hash` to compare against `Set`.
- Use `Set.has` …
=> Optimize a bunch of stuff

links/main.css, rotonde.js, scripts/entry.js, scripts/feed.js, scripts/operator.js
Clicking on an image enlarges the picture.
You can still scroll down to the entry + thread.
It should work with many `custom.css` themes out of the box:
Code-wise, the feed now has got `bigpicture_show`, `_hide`, `_toggle`, `_refresh` and `is_bigpicture`. `_show` and `_toggle` take either the raw HTML to enlarge, or a generator function (used again on `refresh`, useful for entries).
CSS-wise, it's a horrible mess depending on constants:
```css
/* In case questions arise:
* Top is: Center of view = (.entry.top) - 50vh + entry peeking height
* The maximum height is: view height - operator height - entry peeking height - padding
* This is horrible.
* -ade
*/
body #feed .bigpicture > .entry .media { position: absolute; top: calc(-50vh + 60px); left: 50%; margin: 0; transform: translate(-50%, …
```
=> Implement "big picture"

links/main.css
Sets `max-height: 400px` and centers the media horizontally (relative to where it would be if it was a perfect fit).
=> Add max height for media

links/main.css, scripts/entry.js, scripts/feed.js, scripts/operator.js, scripts/portal.js, service.json
rotonde-client now has got a `service.json` for any service messages, i.e. changelog entries.
This also adds back the "welcome" message and adds the option to `filter:rotonde` (suggested action when clicking on `$rotonde`):
Quoting is functional and is handled properly... as long as `r.client_url` stays the same.
~~Possible fix: When quoting `$rotonde` messages, replace the URL with `$rotonde`, functional across portals with different client forks.~~  
Done.
=> Implement basic changelog & service messages in feed

rotonde.js, scripts/feed.js
Pressing the ESC key in big picture now closes it, while clicking on an empty space inside the entry won't close it anymore.
Also, pressing F5 now refreshes the feed. Beaker didn't even refresh the page ¯\\\_(ツ)\_/¯
=> Escape closes big picture, clicking on entry doesn't

scripts/operator.js
Small quality of life addition: Copy-pasting an image in the clipboard (from f.e. GIMP or by taking a screenshot) into the operator now behaves the same as when dropping an image into the operator.
The only change is that the file name is `clipboard-TIMESTAMP.TYPE`, where `TYPE` is determined from the clipboard item type and `TIMESTAMP` is `Date.now()`.
=> Allow pasting images from clipboard

scripts/entry.js, scripts/feed.js, scripts/operator.js, scripts/portal.js
Additionally replaces a few `indexOf`s with `has_hash`, fixes zombie posts hanging around and removes $rotonde from the Portals tab (those fixes could be separated and applied to master, but aren't critical).
Portal now has got a basic `onparse` handler array, which should contain functions in the format of `(json) => {...; return true / false;}`, `true` meaning that the portal will be registered, `false` meaning that the portal will be ignored. `this` is the portal the handler's running against at the moment.
The connection queue now accepts objects with `url` and optional `oncreate` and `onparse` handlers. `oncreate` allows setting `is_remote = true;` early enough.
=> Add very basic "event" handling in Portal.js; Build sameAs on it

scripts/operator.js
Cherry-picked this from #157 as it's a little more critical than the other fixes.
Quoting f.e. `0x0ade/test-a-3` (3rd message from 0x0ade/test-a) was impossible before. The options string was split, [0] was used as the portal name (`0x0ade/test`) and [1] was used as the ref id (`a`). This PR replaces that with
```js
var {name, ref} = r.operator.split_nameref(option);
```
where `split_nameref` uses everything past the last `-` as the ref id.
=> Fix quoting from portals with - in name

scripts/entry.js, scripts/feed.js, scripts/operator.js, scripts/portal.js
As described in [#147](https://github.com/Rotonde/rotonde-client/issues/147#issuecomment-345389579) `sameAs` is an extension to portal.json. 
It adds an array `sameAs` that contains entries to other portals. If those portals in turn have your portal in their `sameAs` arrays, you are considered **remotes** of each other. 
The entire point is to decouple your Rotonde portal from a single machine. Using this feature you can now:
* see the same feed as your remotes
* others following your portal will see the posts you make **from remotes**
* mentions to either the source portal or its remotes will be visible in the mentions tab
If your main portal is `dat://7f2ee...0c5/` and your work computer has a portal at `dat://3ba71...829/`
1. Visit your main portal at `dat://7f2ee...0c5/` and run …
=> Implements sameAs to use Rotonde from multiple machines

links/main.css, rotonde.js, scripts/entry.js, scripts/oembed.js, scripts/oembed_providers.js, scripts/oembed_sandbox.js, scripts/oembed_sandbox_jsonp.js, scripts/operator.js
This PR adds some basic oembed support. Embeds load lazily to prevent anything bad(tm) from happening.
The iframes are sandboxed with the following permissions: `allow-popups allow-scripts allow-same-origin`
`allow-same-origin` allows accessing `localStorage` / `cookies`, which is required by some providers.
The oembed provider list is a reduced set, based on the list from https://github.com/nfl/jquery-oembed-all (MIT-licensed, sourced).
Unfortunately some content providers aren't supported yet, though, as they require some additional processing. This PR should provide a good enough baseline, though.
(At the moment, "Content not supported" is also the generic error message.)
=> Add oembed support

rotonde.js, scripts/entry.js, scripts/feed.js, scripts/home.js, scripts/operator.js, scripts/portal.js, scripts/rdom.js, scripts/status.js, scripts/util.js
This PR adds rdom.js, a very lightweight DOM manipulation "framework" (collection of common functions).
Technically, all the functions were already present in rotonde in one form or another. rdom just collects them all and makes them available in a general purpose manner. Also, it makes DOM manipulation less witchcraft-y. For example, we don't need to pass negative values as indices to remove elements anymore: we've got `rdom_remove` and when adding elements in a loop, `rdom_cleanup` removes anything we `continue`d over.
- `rdom_add(container, ref, index, html)`: Adds the `html` of `ref` to `container` at `index`. If an element for `ref` already exists, it updates it and removes it if required.
- `rdom_remove(container, ref)`: Removes the element belonging to `ref` from `container` and …
=> Add rdom.js

scripts/operator.js
Fixes #167.
I accidentally introduced this bug while changing how quoting yourself should preserve the previously quoted target. While it worked (quotes quoting quotes finally properly targetted the previous author), I completely forgot that `target[0]` was being used for quote attribution in threads.
I'm sorry for having introduced the bug earlier.
=> Fix quote attribution

links/main.css, scripts/entry.js, scripts/home.js, scripts/operator.js
- Embeds are being detected in `entry.to_html`, which only runs when the entry `is_visible` and being rendered to the page.
- Setting `discoverable` to `false` in your portal.json hides it from discovery.
- This can easily be done via `edit:discoverable true / y / yes / false / f / no`
=> Detect embeds when rendering and allow discoverable: false in portal.json

scripts/entry.js, scripts/status.js
1. Substringing the escaped HTML can result in substring cutting off in the middle of an escape sequence.
2. The vulnerabilities in entry.js keep coming >.<
> #<SCRIPT>ALERT("OHNO")</SCRIPT>
=> Fix escaping in status.js and topic XSS in entry.js

README.md
Even though the on-boarding process is much simpler these days, if new users don't know about the site, they're never going to use it. This update points them straight to it.
I would also recommend adding it to the "site" field for this repo.
=> Update Readme to reflect latest onboarding process

scripts/portal.js
Duplicate entries are two entries with the same timestamp (used as ID).
Right now, the most common source for duplicates are legacy posts, existing in your profile.json / portal.json and automatically copied in /posts/, thus counting twice.
=> Ignore duplicate entries

scripts/entry.js, scripts/feed.js, scripts/portal.js
"Lazy quote resolves" occur:
- **Rotonde-style quotes (quote in data):** To fetch the `.name` and `.avatar` fields from the profile.
- **Fritter-style replies (threadParent URL in data):** To fetch the thread parent and the above profile data.
This PR simplifies the previous lazy resolving mess and reduces the amount of required feed refreshes by lazily refreshing.
A lazy feed refresh occurs after a given timeout. If another lazy feed refresh occurs before the timeout, the lazy refresh gets delayed. If a normal feed refresh occurs before the timeout, the lazy feed refresh gets canceled.
~~Just make me a member of the Rotonde "organization" please.~~
=> Better lazy quote resolves
