README.md

Modified instances of 'dat.js' to 'dat.json'.

Updated the setup instructions to reflect the proper filenames.

---

README.md
scripts/entry.js
scripts/operator.js

fix inline image paths

---

links/main.css

Changed all the px instances for flexible ems and rems that change the design based on the screen size and the root font size. Have also changed all the colors to correspond with the root color variables which will allow for easier user customization.

Responsive CSS and color variables.

---

scripts/entry.js

it was annoying to have to add an @

fix replying when clicking on timestamp

---

scripts/feed.js

Some portals report shortnames instead of dat IDs in the 'dat' field of their portal.json, which messes up the userlist. This loads the dat ID from dat.json instead, which should avoid this problem.

Load canonical URLs for userlist from dat.json

---

scripts/operator.js

fix(Operator): show correct word count when empty

---

.datignore

Add test stuff to .datignore

---

README.md

addition of quote command + instructions (click to auto-insert).

add quote command to readme

---

scripts/feed.js

Before:
After:
Also applied the same fix on the sidebar as well.

Use @ instead of ~ for your own name

---

links/main.css
scripts/operator.js

The max height is currently set to 5 lines, but folks that wanna keep the bar as 1 line tall can cap it with `max-height: 1em` in their custom stylesheet.

Make input field auto expand its height when it's more than one line.

---

scripts/operator.js

Whispering with attached media was throwing an error. Simply reordering the existing lines of code a little seems to remedy the issue.

Attempted Whisper/Media Fix

---

scripts/entry.js

This formats the date as ISO-8601 because it's Objectively Correct.

show local time as a tooltip on each entry's timestamp (#19)

---

scripts/operator.js

As said in #81, this is a preliminary command history proposal. It attempts to be as well-behaved as possible.
There's a command history array, an index pointing at the current item in the history (-1 if a new command has been executed), and a command buffer holding whatever is in the input box, so that no stuff is lost while browsing through previous commands.
I have tested most edge cases, but there might be bugs!
(sorry about the extra spaces on empty lines getting removed, my text editor did that automatically)
EDIT1: I could certainly define some local variables in order to avoid long references to "r.operator.cmd_history..." and so on.

Command history proposal

---

scripts/operator.js

Fixed autocompletion for @ mentions (#83).
I wanted to push this before I started working on handling mentions better.

Basic autocomplete working -- better mentions on the horizon

---

rotonde.js
scripts/entry.js
scripts/feed.js
scripts/home.js
scripts/operator.js
scripts/portal.js

…except that one annoying crash right at the beginning. I have reason to believe that _sometimes_ the motherportal pushes something to the feed that is not an entry. the crash happens *after* the first refresh. refreshes are safe now (thanks to _justified programming_).
…and whispers. I don't use them so I don't know if they work. I think I fixed them, but didn't test.
*everything else works hyper-smoothly*

fixed everything

---

scripts/entry.js

Only the first one showed up before this fix.

Multiple mentions show up in the message header

---

scripts/entry.js

Some (possibly buggy/malformed?) mentions weren't appearing in the mentions tab; this restores them.

fixed missing mentions

---

links/main.css
scripts/feed.js

entries and mentions appear selected at the same time

Bugfix: select one tab at a time

---

.gitignore
dat.json
links/main.css
scripts/feed.js

Fixes errors in 0b00ee1, sorry about that
Also removes `dat.json`, which was in .gitignore but somehow still checked in
Props to @neauoire for the great work!

Bugfix: fix Entries tab

---

scripts/feed.js
scripts/home.js

I'm limited to the MGit Android app at the moment. It jumps around, the Android autocomplete interrupts me, but it works™.
* (Delayed) refresh feed on save
* Finish discovery implementation

Bring missing implementations over from rotonde-mod 0.1.3

---

links/main.css
scripts/entry.js
scripts/feed.js

@neauoire wanted a whispers tab, so here's a whispers tab ;)

Implement whispers tab

---

index.html
site/scripts.js
site/styles.css

This pull-request fixes some issues that appeared when simplifying the on boarding page.

Simplified site cleanup

---

site/scripts.js
site/styles.css
template/LICENSE
template/README.md
template/index.html
template/links/custom.css
template/media/content/icon.svg

This pull request essentially moves `rotonde-portal` into this repository and uses it as a template when create new portals with the onboarding site. This avoids having to fork and clean up @neauoire's portal. I've also added a "loading" state while checking to make sure all files are present before moving forward.

Stop forking neauoire and use a template instead

---

scripts/feed.js

Pulls updates from portals when receiving "invalidated" events.

Fix refresh on activity

---

links/night_mode.css
scripts/operator.js

this adds the command `night_mode` which inverts all colors (except for media attachments)

night mode

---

README.md

README: add hashbase instructions

---

scripts/entry.js

This makes it easier to make threads / quote yourself, by separating the edit link from the timestamp.

add edit link

---

scripts/entry.js

We're missing in a few places. ..

escape operations

---

links/main.css
scripts/entry.js

Fixes the style and layout of the message tools. The edit tool was a timestamp and the del tool was hidden behind the link dot.

Fix message tools

---

links/main.css
links/night_mode.css
scripts/entry.js
scripts/operator.js

`376b91c`: quoting a quote that quoted an entry with media attachment broke the link to that media attachment → fixed!
`8c9a4ea`: quoting one's own entries to make a thread cluttered up the mentions → fixed!
`07e420b`: rewrote the night mode implementation according to @0x0ade's suggestion

some fixes

---

links/main.css

fixed hues in night mode

---

scripts/entry.js

As per @Luxizzle's feedback on rotonde:

Always add quote "tool" to messages

---

links/main.css
scripts/entry.js
scripts/operator.js

- Mentioning someone in a quote adds them to the targets
- Whispers are quotable; Quoting whispers makes the quote a whisper, too
- Tools in whisper messages are white when hovering (previously black text on black background)
- Filtering now uses `toLowerCase` before checking if the filter string exists.
- Trailing `.,;"{}`s from hashtags are ignored.

Minor improvements

---

links/main.css
rotonde.js
scripts/entry.js
scripts/feed.js
scripts/home.js
scripts/operator.js

Pinning one of your entries as the first entry in the feed. Twitter has this feature, so why don't we have? You can pin an entry with the ```pin:id``` command, haven't added the PIN and UNPIN buttons to the tools part of an entry, because I didn't know if you want it there 😄 
Clicking on the ```message``` div of the paginator was buggy, so I've fixed it.

Pinning entries & a bugfix

---

links/main.css
scripts/entry.js
scripts/portal.js

It was actually a simple typo...

Bigpicture bugfix

---

scripts/entry.js
scripts/operator.js

Added the username autocomplete to the ```whisper``` command too.

Autocomplete whispers + self-quoting bugfix

---

links/main.css
scripts/entry.js
scripts/feed.js
scripts/home.js
scripts/operator.js
scripts/portal.js

Discovery Channel

---

scripts/feed.js
scripts/home.js
scripts/operator.js
scripts/status.js

Only discover in background after finishing loading the main feed

---

scripts/status.js

using localStorage to track status open / close state between browser refreshes
I like having the status always open, this allows the user to decide !

persistent status.enabled

---

scripts/entry.js
scripts/portal.js

Turns out `status.js` wasn't the only vulnerable place.

Fix XSS holes in entry.js

---

links/main.css
scripts/entry.js
scripts/feed.js

Fixes embedded images from f.e. imgur in fullscreen mode ("big picture") and unnecessary DOM refreshes (big picture DOM got invalidated with every feed refresh).

Fix embedded big pictures and redundant DOM invalidations

---

rotonde.js
scripts/entry.js
scripts/portal.js

Also replaces spaces with underscores for better Fritter compatibility.

Fix bumps, tags

---

scripts/entry.js

I think it would be better if links in the entries would open in new tab.

microcommit: open links in new tab
